import jinja2
import nox

# imports all nox task provided by the toolbox
from exasol.toolbox.nox.tasks import *

from exasol.mlflow_plugin import rest_api
from exasol.mlflow_plugin.deploy import adapter_impl
from exasol.mlflow_plugin.deploy.udfs import Deployable
from exasol.mlflow_plugin.slc import slc_build_context

# default actions to be run if nothing is explicitly specified with the -s option
nox.options.sessions = ["format:fix"]


from pathlib import Path

from noxconfig import PROJECT_CONFIG


@nox.session(name="slc:export", python=False)
def slc_export(session: nox.Session):
    """
    Build and export an SLC Image to directory ``.slc``.
    """
    export_path = PROJECT_CONFIG.root_path / ".slc"
    with slc_build_context() as builder:
        builder.export(export_path)


ANCHORS = {
    "experiments/search": "search-experiments",
    "runs/search": "search-runs",
    "registered-models/search": "search-registeredmodels",
    "registered-models/get-latest-versions": "get-latest-modelversions",
    "registered-models/get": "get-registeredmodel",
    "model-versions/search": "search-modelversions",
    "model-versions/get": "get-modelversion",
    "model-versions/get-download-uri": "get-download-uri-for-modelversion-artifacts",
    "gateway/endpoints/list": "list-gateway-endpoints",
    "gateway/model-definitions/list": "list-gateway-model-definitions",
    "artifacts": "mlflowartifactsmlflowartifactsservicelistartifacts",
}


def _generated_file_header(session_name: str, eol_comment: str) -> str:
    return (
        f"{eol_comment} This file is generated by nox -s {session_name}.\n"
        f"{eol_comment} Do not edit!\n"
    )


def _describe_endpoint(
    template: jinja2.environment.Template, ep: rest_api.Endpoint
) -> str:
    args = ", ".join(col.name for col in ep.input_columns)
    input_columns = [(c.sql_name, c.sql_type, c.comment) for c in ep.input_columns]
    output_columns = [(c.sql_name, c.sql_type) for c in ep.total_output_columns]
    return template.render(
        udf_name=ep.var_name,
        underline="-" * (len(ep.var_name) + 8),
        udf_args=args,
        endpoint=ep.url_suffix,
        anchor=ANCHORS[ep.url_suffix],
        input_columns=input_columns,
        output_columns=output_columns,
    )


@nox.session(name="docs:update", python=False)
def docs_update(session: nox.Session):
    """Update UDFs in user guide."""

    path = PROJECT_CONFIG.root_path / "doc/user_guide/access_mlflow"
    env = jinja2.Environment()
    tmpl_str = (path / "template_rest_endpoints.jinja").read_text()
    template = env.from_string(tmpl_str)
    path = path / "rest_endpoints.rst"
    session.log(f"Updating UDFs in {path.relative_to(PROJECT_CONFIG.root_path)}")
    header = _generated_file_header("docs:update", eol_comment="..")
    with path.open("w") as f:
        print(header, file=f)
        for ep in rest_api.ALL_ENDPOINTS:
            print(_describe_endpoint(template, ep), file=f)


LANGUAGE_ALIAS = "EXA_MLFLOW"


@nox.session(name="code:generate", python=False)
def code_generate(session: nox.Session):
    """Generate deploy/extension.sql"""

    path = Path("exasol/mlflow_plugin/deploy/extension.sql")
    session.log(f"Updating SQL script {path}")
    path = PROJECT_CONFIG.root_path / path
    all_udfs = [Deployable(LANGUAGE_ALIAS, "", e) for e in rest_api.ALL_ENDPOINTS]
    adapter = adapter_impl.create_adapter(schema="", language_alias=LANGUAGE_ALIAS)
    header = _generated_file_header("code:generate", eol_comment="--")
    with path.open("w") as f:
        print(header, file=f)
        for udf in all_udfs:
            print(udf.sql, "\n", file=f)
        print(adapter.sql, file=f)


@nox.session(name="generated-files:check-outdated", python=False)
def check_outdated(session: nox.Session):
    """
    Update generated files and run git diff to verify if any of them was
    outdated.
    """
    code_generate(session)
    docs_update(session)
    session.run("git", "diff", "--exit-code", ".")
