import jinja2
import nox

# imports all nox task provided by the toolbox
from exasol.toolbox.nox.tasks import *

from exasol.mlflow_plugin import rest_api
from exasol.mlflow_plugin.rest_api import vs_impl
from exasol.mlflow_plugin.rest_api.udf.deployment import Deployable
from exasol.mlflow_plugin.slc import slc_build_context
from exasol.mlflow_plugin.virtual_schema.deployment import Adapter

# default actions to be run if nothing is explicitly specified with the -s option
nox.options.sessions = ["format:fix"]


from pathlib import Path

from noxconfig import PROJECT_CONFIG


@nox.session(name="slc:export", python=False)
def slc_export(session: nox.Session):
    """
    Build and export an SLC Image to directory ``.slc``.
    """
    export_path = PROJECT_CONFIG.root_path / ".slc"
    with slc_build_context() as builder:
        builder.export(export_path)


ANCHORS = {
    "experiments/search": "search-experiments",
    "runs/search": "search-runs",
    "registered-models/search": "search-registeredmodels",
    "registered-models/get-latest-versions": "get-latest-modelversions",
    "registered-models/get": "get-registeredmodel",
    "model-versions/search": "search-modelversions",
    "model-versions/get": "get-modelversion",
    "model-versions/get-download-uri": "get-download-uri-for-modelversion-artifacts",
    "gateway/endpoints/list": "list-gateway-endpoints",
    "gateway/model-definitions/list": "list-gateway-model-definitions",
    "artifacts": "mlflowartifactsmlflowartifactsservicelistartifacts",
}


def _update_udf_docs(session: nox.Session):
    path = PROJECT_CONFIG.root_path / "doc/user_guide/access_mlflow"
    env = jinja2.Environment()
    tmpl_str = (path / "template_rest_endpoints.jinja").read_text()
    template = env.from_string(tmpl_str)
    path = path / "rest_endpoints.rst"
    session.log(f"Updating UDFs in {path.relative_to(PROJECT_CONFIG.root_path)}")
    for ep in rest_api.ALL_ENDPOINTS:
        args = ", ".join(col.name for col in ep.input_columns)
        input_columns = [(c.sql_name, c.sql_type, c.comment) for c in ep.input_columns]
        output_columns = [(c.sql_name, c.sql_type) for c in ep.total_output_columns]
        result = template.render(
            udf_name=ep.var_name,
            underline="-" * (len(ep.var_name) + 8),
            udf_args=args,
            endpoint=ep.url_suffix,
            anchor=ANCHORS[ep.url_suffix],
            input_columns=input_columns,
            output_columns=output_columns,
        )
    path.write_text(
        f".. This file is generated by nox -s {session.name}.\n"
        ".. Do not edit!\n\n"
        f"{result}"
    )


LANGUAGE_ALIAS = "EXA_MLFLOW"


def _update_deployment_sql(session: nox.Session):
    path = Path("doc/user_guide/installation/deployment.sql")
    session.log(f"Updating SQL script {path}")
    path = PROJECT_CONFIG.root_path / path
    all_udfs = [Deployable(LANGUAGE_ALIAS, "", e) for e in rest_api.ALL_ENDPOINTS]
    adapter = Adapter(
        schema="",
        name="MLFLOW_VIRTUAL_SCHEMA_ADAPTER",
        impl=vs_impl.ADAPTER_IMPL,
        language_alias=LANGUAGE_ALIAS,
    )
    with path.open("w") as f:
        print(
            f"-- This file is generated by nox -s {session.name}.\n"
            "-- Do not edit!\n",
            file=f,
        )
        for udf in all_udfs:
            print(udf.sql, "\n", file=f)
        print(adapter.sql, file=f)


@nox.session(name="docs:update", python=False)
def docs_update(session: nox.Session):
    """
    Updated the generated parts in the documentation.
    """
    _update_deployment_sql(session)
    _update_udf_docs(session)
