name: Spike

on:
  workflow_call:

jobs:
  Spike:
    name: Spike
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

#       - name: Failing
#         run: |
#           echo "This is a step intentionally failing..."
#           false
#
#       - name: Follow-up Step
#         if: always()
#         run: echo "This is a follow-up step after the failing one..."

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v4

      # Each of the following steps is annotated with if: always()
      # running the check even if one of the preceding checks failed.

      - name: Check Version(s)
        run: poetry run -- nox -s version:check

      - name: Build Documentation
        if: always()
        run: poetry run -- nox -s docs:build

      - name: Link Check
        if: always()
        run: poetry run -- nox -s links:check

      - name: Run lint
        if: always()
        run: poetry run -- nox -s lint:code

      - name: Run type-check
        if: always()
        run: poetry run -- nox -s lint:typing

      - name: Run security linter
        if: always()
        run: poetry run -- nox -s lint:security

      - name: Run format check
        if: always()
        run: poetry run -- nox -s format:check

      - name: Run Distribution Check
        if: always()
        run: poetry run -- nox -s package:check

      - name: Run Tests and Collect Coverage
        if: always()
        run: poetry run -- nox -s test:unit
